name: build on windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v5
        with:
          repository: NetHack/NetHack
          submodules: true

      - name: msvcsetup
        uses: ilammy/msvc-dev-cmd@v1

      - name: nhsetup
        run: |
          cd sys\windows
          .\nhsetup.bat

      - name: buildmain
        run: |
          cd src
          nmake package

      - name: tag
        uses: EndBug/latest-tag@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        uses: ncipollo/release-action@v1
        with:
          name: "latest"
          allowUpdates: true
          tag: latest
          commit: jnh
          replacesArtifacts: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: package/nethack-370-win-x64.zip
