name: build on windows

on:
  workflow_dispatch:
  schedule:
    - cron: "13 6 * * *"

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v5

      - uses: actions/checkout@v5
        with:
          repository: NetHack/NetHack
          path: nh
          submodules: true

      - name: msvcsetup
        uses: ilammy/msvc-dev-cmd@v1

      - name: nhsetup
        run: |
          cd nh\sys\windows
          .\nhsetup.bat

      - name: buildmain
        run: |
          cd nh\src
          nmake package

      - name: tag
        uses: EndBug/latest-tag@latest

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: latest
          replacesArtifacts: true
          artifacts: nh/package/nethack-370-win-x64.zip
